name: Auto Git Tag

on:
  push:
    branches:
      - main

jobs:
  copy-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0   # important: we need full history + tags

      - name: Detect PR number from squash commit
        id: pr
        run: |
          PR_NUMBER=$(git log -1 --pretty=%B | sed -n 's/.*#\([0-9]\+\).*/\1/p')
          if [ -z "$PR_NUMBER" ]; then
            echo "No PR number found in commit message. Skipping..."
            echo "pr_number=" >> $GITHUB_OUTPUT
          else
            echo "Detected PR: #$PR_NUMBER"
            echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          fi

      - name: Get tag from PR head commit
        id: get_tag
        if: steps.pr.outputs.pr_number != ''
        run: |
          # Fetch PR metadata from GitHub
          PR_HEAD_SHA=$(gh pr view ${{ steps.pr.outputs.pr_number }} --json headRefOid -q .headRefOid)

          echo "PR head commit SHA: $PR_HEAD_SHA"

          TAG=$(git tag --points-at $PR_HEAD_SHA | head -n 1 || true)

          if [ -z "$TAG" ]; then
            echo "No tag found on PR head commit. Skipping..."
            echo "tag=" >> $GITHUB_OUTPUT
          else
            echo "Found tag: $TAG"
            echo "tag=$TAG" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move tag to squash commit
        if: steps.get_tag.outputs.tag != ''
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          MERGE_COMMIT=$(git rev-parse HEAD)
          echo "Moving tag '${{ steps.get_tag.outputs.tag }}' → $MERGE_COMMIT"

          git tag -f ${{ steps.get_tag.outputs.tag }} $MERGE_COMMIT
          git push origin ${{ steps.get_tag.outputs.tag }} -f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
