name: Auto Git Tag

on:
  push:
    branches:
      - main

jobs:
  copy-single-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get the merged commit (feature branch single commit)
        id: get_parent
        run: |
          MERGE_COMMIT=$(git rev-parse HEAD)
          PARENT_COMMIT=$(git rev-parse $MERGE_COMMIT^2)
          echo "parent_commit=$PARENT_COMMIT" >> $GITHUB_OUTPUT

      - name: Get the single tag from feature commit
        id: get_tag
        run: |
          TAG=$(git tag --points-at ${{ steps.get_parent.outputs.parent_commit }})
          echo "Found tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Move that tag to main merge commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@af.noreply.github.com"
          git tag ${{ steps.get_tag.outputs.tag }} -f
          git push origin ${{ steps.get_tag.outputs.tag }} -f
