name: Auto Git Tag

on:
  push:
    branches:
      - main

jobs:
  copy-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # so tags are included

      - name: Find PR that triggered this push
        id: pr
        uses: actions-ecosystem/action-get-merged-pull-request@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tag from PR branch head commit
        id: get_tag
        run: |
          PR_BRANCH=${{ steps.pr.outputs.head_ref }}
          echo "Checking branch: $PR_BRANCH"

          # Fetch tags from the PR branch
          git fetch origin $PR_BRANCH --tags

          # Get commit id of the PR branch head
          PR_COMMIT=$(git rev-parse origin/$PR_BRANCH)
          echo "PR_COMMIT=$PR_COMMIT"

          # See if that commit has a tag
          TAG=$(git tag --points-at $PR_COMMIT | head -n 1 || true)

          if [ -z "$TAG" ]; then
            echo "No tag found on PR branch commit. Skipping..."
            echo "tag=" >> $GITHUB_OUTPUT
          else
            echo "Found tag: $TAG"
            echo "tag=$TAG" >> $GITHUB_OUTPUT
          fi

      - name: Copy tag to merge commit on main
        if: steps.get_tag.outputs.tag != ''
        run: |
          git config user.name "github-actions
          git config user.email "github-actions@af.noreply.github.com"

          MERGE_COMMIT=$(git rev-parse HEAD)
          TAG=${{ steps.get_tag.outputs.tag }}

          echo "Tagging merge commit $MERGE_COMMIT with $TAG"
          git tag -f $TAG $MERGE_COMMIT
          git push origin -f $TAG
